# Generated by Django 3.0.4 on 2020-03-14 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('date_of_creation', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_of_creation', models.DateTimeField(auto_now_add=True)),
                ('tag', models.ManyToManyField(blank=True, related_name='tasks', to='tasks.Tag')),
            ],
        ),
        migrations.AddField(
            model_name='tag',
            name='task',
            field=models.ManyToManyField(related_name='tags', to='tasks.Task'),
        ),
    ]
