# Generated by Django 3.0.4 on 2020-03-14 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20200314_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='task',
            field=models.ManyToManyField(blank=True, related_name='tags', to='tasks.Task'),
        ),
    ]
